version: "3"

services:
  ionicapp:
    build:
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
      target: dev_base
    restart: "no"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=300
    ports:
      - "5000:5000"
      - "8100:8100"
      - "8200:8200"
    volumes:
      - ..:/workspace
    command: /bin/sh -c "while sleep 1000; do :; done"
